steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/k8s-assignment-428917/k8s-repo/k8s-container2:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/k8s-assignment-428917/k8s-repo/k8s-container2:latest",
      ]
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=service2-deployment.yaml
      - --location=us-central1-a
      - --cluster=k8s-cluster
      - --output=output/deployment
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=service2-service.yaml
      - --location=us-central1-a
      - --cluster=k8s-cluster
      - --output=output/service
options:
  logging: CLOUD_LOGGING_ONLY
